# image: drupalpod/drupalpod-gitpod-base:20220322

tasks:

  - before:    
      # gp sync-await beforebuild &&
      bash .beforebuild.sh &&
      gp sync-done beforebuild

    init: 
      gp sync-await prebuild &&
      bash .prebuild.sh 
      # gp sync-done prebuild
    command: ddev launch



