image: drud/ddev-gitpod-base:latest
additionalRepositories:
  - url:  {{MAIN_REPO}}
    checkoutLocation: fullstack-backend


tasks:
  - init: bash .prebuild.sh
    command: ddev launch
    env:
      MAIN_REPO: https://github.com/ibrah3m/IQdevs

# mainConfiguration: MAIN_REPO

