# image: drupalpod/drupalpod-gitpod-base:20220322

tasks:

  # - before:    
      

  - init: |
      bash .beforebuild.sh 
      gp sync-done beforebuild 
      gp sync-await beforebuild
      bash .prebuild.sh 
    command: ddev launch



