# image: drupalpod/drupalpod-gitpod-base:20220322

tasks:

  # - before:    
      # gp sync-await beforebuild &&
      

    init: |
      bash .beforebuild.sh &&
      gp sync-done beforebuild
      gp sync-await beforebuild &&
      bash .prebuild.sh 
      # gp sync-done prebuild
    command: ddev launch



