# image: drupalpod/drupalpod-gitpod-base:20220322

tasks:

  - before:    
      gp sync-await beforebuild &&
      bash .beforebuild.sh
    init: 
      gp sync-await prebuild &&
      bash .prebuild.sh 
    command: ddev launch



